import random
def psuper(a,b,c):
  x = random.randint(40,90)
  y = random.randint(1,10)
  z = random.randint(1,90)
  print("\033[1;34m\nI numeri vincenti sono:")
  print("\033[0;31m")
  print(a)
  print(b)
  print(c)
  print(x)
  print(y)
  print(z)
def winfgen():
  x = random.randint(1,2)
  y = random.randint(3,4)
  z = random.randint(5,6)
  a = random.randint(7,8)
  b = random.randint(9,10)
  c = random.randint(11,12)
  d = random.randint(13,14)
  e = random.randint(15,16)
  f = random.randint(17,18)
  g = random.randint(19,20)
  print(a)
  print(b)
  print(c)
  print(d)
  print(e)
  print(f)
  print(g)
  print(x)
  print(y)
  print(z)